### ISSUE TITLE
completely disable automatic repositioning

### ISSUE THREAD

**Issue by rossi-jeff** [enyo/opentip#102]
I am trying to implement opentips as info windows on google maps, because google decided that info windows should cover the markers for whatever reason.

I have managed to get positioning working pretty well using map event listeners.

I have both containInViewport and autoOffset set to false, but if you scroll the window the  opentip will still reposition itself, often not on the map, and almost always not where it should be.

What am I missing?

**Comment by enyo** [comment]
That's strange... `containInViewport` should definitely work. Make sure you are using the latest version and that your configuration options are passed properly.
