### ISSUE TITLE
Error: Multiple elements provided.

### ISSUE THREAD

**Issue by hegdeashwin** [enyo/opentip#107]
Hi

My HTML Template code:

```
<span class="tooltip">Open Tip 1</span>
```

As above span is dynamically generated. Thus, It will be multiple as below:

```
<span class="tooltip">Open Tip 1</span>
<span class="tooltip">Open Tip 2</span>
```

my JS code:

```
Opentip.styles.factPopupStyle = {
        extends: "alert",
    stem: true,
    background: '#e48895',
    borderColor: '#e48895',
    borderRadius: 0
};
myTip = new Opentip($('.tooltip'), "Hello World", { style: "factPopupStyle" });
```

When i executed the code it showing me below error:

```
Error: Multiple elements provided.
```

I am not able to figure out that is the issue?

**Comment by enyo** [comment]
If you create a tooltip with `new Opentip` you need to provide only **one** element. Use the jquery adapter (`$('.tooltip').opentip([...]);`) to do what you want, or iterate over all tooltip `div`s and call `new Opentip` multiple times.
