### ISSUE TITLE
Issue while minifying the opentip.js file

### ISSUE THREAD

**Issue by nowol** [enyo/opentip#15]
Hi,

I had an issue while trying to minify opentip.js using the Yui Compressor.  I tracked it down with the help of the Yui Compressor maintainer to the use of the reserved keyword "char" in the dasherize method.

I was wondering if you could change the method dasherize  from this:

```
Opentip::dasherize = (string) ->
  string.replace /([A-Z])/g, (_, char) -> "-#{char.toLowerCase()}"
```

To this:

```
Opentip::dasherize = (string) ->
  string.replace /([A-Z])/g, (_, character) -> "-#{character.toLowerCase()}"
```

Only "char" was renamed.

Thanks!

**Comment by enyo** [comment]
Thanks @nowol !

**Comment by enyo** [comment]
It'll be merged into the master branch and released as a version as soon as I implemented a few other things. So if you want to redownload it, please use the [develop branch](https://github.com/enyo/opentip/tree/develop) for now.

**Comment by nowol** [comment]
Thanks for the quick fix!
