### ISSUE TITLE
hideOn click doesn't work on part of the div

### ISSUE THREAD

**Issue by sbrave** [enyo/opentip#23]
I have a small div (23px by 22px), with a background image, that I'm using as a help icon for users to get inline help within a page.  I'm using showOn=click and hideOn=click.  The showOn=click works fine if I click anywhere inside the div.  Once a tip is showing though, I can only click on half of the div to make it go away.  It takes a while to figure out why the tip isn't going away, so makes for a bad user experience.  Any idea why this is happening?

Here are the relevant portions of my code:

```
tip = new Opentip($("#help-" + attributeId), {  target: true, 
                                                tipJoint: "bottom right", 
                                                targetJoint: "left", 
                                                group: "group-help", 
                                                showOn: "click", 
                                                hideOn: "click" });
tip.setContent(helpDescription);
```

div class='help table_help' id='help-' + attributeId   (sorry can't show the "<" ">", these are created and injected into the DOM)

.help{float:right; width:23px; height:22px; background-image:url(images/help.png);}

**Comment by enyo** [comment]
Is it possible that the shadow of the opentip is actually overlapping the div, thus intercepting all click events? If so, use 2 'hideTriggers'. One should be the trigger like its now, the other should be the tip. This way, clicking on the opentip itself hides it as well.

**Comment by enyo** [comment]
@sbrave did you solve the problem? I'd like to close this issue.

**Comment by sbrave** [comment]
Sorry for the delay.  Yes!  hideTriggers: ["tip", "target"] did it!

**Comment by enyo** [comment]
Great! Have a nice day.
