### ISSUE TITLE
Hideon as Table

### ISSUE THREAD

**Issue by nillerch** [enyo/opentip#31]
Hi
it seems that 
           , hideOn: ['mouseleave','click']
does not work properly, I can can get each of the event to work but I want the hide the, tootltip on both events (the first in the array works) , or am I doing anything wrong ?

thx

Torben

**Comment by enyo** [comment]
It doesn't work this way. If you want multiple hide events, you need multiple hide triggers... It's a bit dumb: use an array of hideTriggers in the option, and then the array for hideOn.

**Comment by enyo** [comment]
PS: Sorry for the late reply. I'm quite busy at the moment.
