### ISSUE TITLE
All of my 'tips' are not populating

### ISSUE THREAD

**Issue by only1chip** [enyo/opentip#32]
Hello,

Opentip is great, thanks for all the hard work on it!  

I have an issue where all of my tool tips are not populating.

Website is here: http://info.automationdirect.com/education/PeachPits/index.html

Each of the small white boxes should have a tooltip... but there are always a few that do not load (it seems random as to which ones do not populate).  The text is coming from an XML file, here is the javascript being used to populate the tips:

``` javascript
for (var i=1;i<=TeamElements.length;i++){
        ...
        //add the tool tips
        detailsPit[i] = document.getElementById('pit'+pitNum[i]);
        tooltipContent[i] = teamName[i] +" <br/><br/>"+teamLocale[i];
        myTip[i] = new Opentip(detailsPit[i], tooltipContent[i], teamNickname[i], { style: 'standard', group: 'container', target: true });
    }
```

Perhaps I'm doing something stupid (or simply a bad practice) here?

Thanks,

Chip

**Comment by enyo** [comment]
Could you try with the jQuery version just to see if it's related to the native adapter?

**Comment by only1chip** [comment]
OK, sorry that took so long.  The page(same link as above) has now been updated to use the jQuerry version of opentip, but there are still quite a few of the 60+ tooltips on the page that do not populate. It still seems a little random as to which ones will populate.  After each refresh the group of tips that do not populate will change.

**Comment by enyo** [comment]
Ok. That's really strange. I'll look into it.

**Comment by enyo** [comment]
For some reason the tooltips stay in an "intermediate" state where they aren't really hidden but invisible. So they block the mouse events for the elements underneath. Still trying to figure out why.

**Comment by enyo** [comment]
@only1chip Please report back if everything works now. It should work with the native adapter as well.

**Comment by only1chip** [comment]
@enyo Yep, it's working now - Thanks!
