### ISSUE TITLE
width not adjusting. getting max 300px

### ISSUE THREAD

**Issue by figfig** [enyo/opentip#33]
Hi. I'm using the native.min script and HTML attributes but I get a wide tooltip with lots of empty space. Think its making it the max-width of 300px i see in the css. Any ideas?

div style="width:44px;" data-ot="testr" data-ot-style="dark" data-ot-target="true" data-ot-tip-joint="top" data-ot-target-joint="bottom" data-ot-contain-in-viewport="false" data-ot-delay="0"...an image.../div

**Comment by enyo** [comment]
Please inspect the element in chrome or firebug and check what
property actually enforces the width. It sure isn't max-width but
maybe you defined a CSS property interfering?

**Comment by figfig** [comment]
Thanks. I already have a class named "content" and opentip uses the same name. I've renamed mine and it works fine now.
