### ISSUE TITLE
HTML element inside tooltips?

### ISSUE THREAD

**Issue by jch02140** [enyo/opentip#43]
Is it possible to show any HTML elements like links, forms, videos, images in the tooltips area?

**Comment by enyo** [comment]
Yes. Just put it in there. You can also provide a function as content that will be executed and where you could create the HTML elements or just the content of another hidden div.

**Comment by kevincberry** [comment]
I'm trying to place a link in the tooltip but not having any success. When I specify an hreft value it seems to be breaking the javascript. I'm new to javascript but any suggestions on how ot properly format the sample code below would be appreciated. 

`var opentip_upcoming_events = new Opentip("#upcoming_events", "Line 1<br>2nd line<br><a href="http://link.com">link.com</a>, "", { style: "tooltip_style" })`
