### ISSUE TITLE
hideOn not working

### ISSUE THREAD

**Issue by shahzebkhan** [enyo/opentip#44]
I am trying to show the tooltip on mouseover, and hide it on mouseout. 

The tooltip shows fine, but never hides. 

I am using coffeescript, and have tried this on latest Firefox, Safari and Chrome versions.

```
myInput = $(".alert")
inputOpentip = new Opentip(myInput,
    title: "Title!!!",
    showOn: "mouseover",
    target: true,
    hideTriggers: ["tip", "trigger", "target"],
    hideOn: "mouseout"
)
```

Am I missing something here ?

**Comment by enyo** [comment]
Try mouseout instead of mouseleave.

**Comment by shahzebkhan** [comment]
Thanks for your response enyo.

I have tried both, but neither worked.

Any other ideas ?

**Comment by shahzebkhan** [comment]
Does the order in which these options are specified, matter at all ?

**Comment by shahzebkhan** [comment]
Managed to resolve it. 

I don't think it was ever a problem with OpenTip, but a weirdness with how I had included the CSS file. 

Thanks for your response enyo. Closing the issue.

**Comment by enyo** [comment]
Glad you resolved it! Btw: the order does not matter at all, no. In general, [plain JS objects have no ordered properties](http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) so it wouldn't even be possible for me make the order matter.

**Comment by shahzebkhan** [comment]
Thanks for the info!
