### ISSUE TITLE
How can I trigger opentip to recalculate the size of the tooltip?

### ISSUE THREAD

**Issue by jaacob** [enyo/opentip#45]
I'm pulling in a form template via ajax; the template contains three separate forms that can be switched between using a nav pillbox at the top of the tooltip to show/hide the active form.

I need to trigger opentip to resize the tooltip when the pillbox nav options are clicked, because the forms are of various sizes.

Is there a function I can execute to trigger the visible tooltip's canvas to recalculate its width/height to contain the visible markup?

**Comment by enyo** [comment]
I think `_storeAndLockDimensions()` and `.reposition()` should do the trick.
