### ISSUE TITLE
Issue to format/wrap properly long text into a Tooltip popup.

### ISSUE THREAD

**Issue by SimoneTaliercio** [enyo/opentip#47]
Hi All,

I would ask how works the algorithm which is in charge to display properly long text. In fact, I'm experiencing some issue with 'strange' file names. Those file names are programmatically used as text for a tooltip. See the screenshot for more detail.

Thanks for the support and overall the GREAT job done behind this plugin and dropzonejs!

Kind Regards,
Simone

![Screen shot 2013-04-15 at 10 51 22 AM](https://f.cloud.github.com/assets/3648619/386758/326b1324-a6af-11e2-8bd1-d50b7d2bfd20.png)

**Comment by enyo** [comment]
Hi 
This is mostly done with CSS. There's a max-width property that's why it doesn't resize more. You can just overwrite the max-width if you want the tooltip to be wider. Or you could check for long words and add a space yourself. 

Glad you like my work!

Cheers

**Comment by SimoneTaliercio** [comment]
Thanks Matias for your fast reply!

Tomorrow morning I'll try to play around with the max-width property.

And, I don't like your work... I love it! ;-)
