### ISSUE TITLE
OpenTip ajax option

### ISSUE THREAD

**Issue by nuriel16** [enyo/opentip#49]
Hi, 

I want to use OpenTip project in my program,
but I encountered in a problem:

On the new OpenTip() command' when I set the ajax option to 'true', instead of present the text I have on the URL, it sais that: "There was a problem downloading the content".

Maybe I doing it wrong. 
Can you please give me an example of how it supposed to be written?
Or any other help?

Thanks & Regards,
Nuriel

**Comment by nuriel16** [comment]
I forgot to say that I don't have this problem on link element (which the value of ajax option is 'true'), but only when ajax option is 'String'.

**Comment by nuriel16** [comment]
The problem was solved.
I didn't know that I should set the ajax option value itself with the url. I thought it should be valued with the key word 'String' and the url is taken from the function arguments.

Thank any way,
Nuriel

**Comment by nuriel16** [comment]
Hi again,

I wanted to know please if there an option to present an image onto the tooltip by ajax or somehow else.
Up to now, I didn't make it.

Thanks,
Nuriel

**Comment by enyo** [comment]
@nuriel16  Just set the HTML `<img ....` as tooltip content.
