### ISSUE TITLE
Opentip on disabled form element

### ISSUE THREAD

**Issue by chrilleferna** [enyo/opentip#51]
Hi Matias!

I noticed that if you attach an opentip to a form element (in my case a radio button), the tip stops showing if you disable that element. In my case I would like to pop up an explanation to the user for why the radio button is disabled. Is this a possible change?

Cheers and thanks for a very useful library
  -- christer

**Comment by enyo** [comment]
Hi... that should definitely not be the case. How do you disable the button?

**Comment by chrilleferna** [comment]
With a jQuery call to set the disabled attribute to true:

$('tr.disabled_presence_row .status_2').attr('disabled',true);

**Comment by enyo** [comment]
If you reenable the element, does the tooltip work again?

**Comment by chrilleferna** [comment]
Yes it does:

$('tr.disabled_presence_row .status_2').attr('disabled',true);
$('tr.disabled_presence_row .status_2').attr('disabled',false);

and it works again

**Comment by enyo** [comment]
That is weird. Which browser are you using?

**Comment by chrilleferna** [comment]
Safari on osx. Let me try on Firefox - hang on...

**Comment by chrilleferna** [comment]
same thing with Firefox

**Comment by chrilleferna** [comment]
maybe all events are disabled on disabled elements, including focus?

**Comment by enyo** [comment]
http://stackoverflow.com/questions/3100319/event-on-a-disabled-input

This is a browser issue. Sorry ;)

**Comment by chrilleferna** [comment]
OK, so that explains it. The solution proposed on stackoverflow: "I can't think of a better solution but, for complete cross browser compatibility, you could place an element in front of the disabled input and catch the click on that element." was also the workaround I planned to use.

Thanks for your help!

**Comment by enyo** [comment]
No problem. I'd try attaching Opentip to the container element of your select box, and see if mouse events bubble to the parent in recent versions of FF. (The answer on stackoverflow is pretty old)

**Comment by chrilleferna** [comment]
Yes, I did that already and it works, but in my quick fix the radio button is on top of the container so when you hover right above it, the tooltip doesn't show, There was a link on stackoverflow to a quite nice solution, where you have jQuery inserting an overlay element: http://blog.pengoworks.com/index.cfm/2010/4/23/Attaching-mouse-events-to-a-disabled-input-element
