### ISSUE TITLE
ajax response processing

### ISSUE THREAD

**Issue by ozyn** [enyo/opentip#52]
I want to use openTip in conjunction with Ajax. My ajax call returns a JSON object that I format on the client. I see in the code that the ajax call directly sets the content in the opentip popup (line 1195):
      onSuccess: function(responseText) {
        //….
        return _this.setContent(responseText);

What I want would be more like
      onSuccess: function(responseText) {
        //….
        return _this.setContent(myCallBackFunction(responseText));

Also, I’d want to pass other parameters to the Ajax call.

Are those possible?

**Comment by enyo** [comment]
Mh.. there's no built in function for that. But you can "enhance" Opentip for that.

Example:

``` js
var originalSetContentFunction = Opentip.prototype.setContent;
Opentip.prototype.setContent = function(content) {
  // Do anything you want with the content, or call callbackFunctions.

  // Invoke the original setContent() function which will make sure to update the content and reposition
  // opentip properly.
  originalSetContentFunction.call(this, content);
};
```

Hope that helps.
Cheers
