### ISSUE TITLE
`data-ot-tipJoint` and `data-ot-targetJoint` not being recognized

### ISSUE THREAD

**Issue by sethwoodworth** [enyo/opentip#53]
`<i data-ot="Upload directly to this course" data-ot-target="true" data-ot-tipjoint="top center" data-ot-targetjoint="bottom center" class="icon-upload"></i>`

![screenshot from 2013-05-23 17 00 08](https://f.cloud.github.com/assets/123998/557161/fe4c8118-c3eb-11e2-8a7f-b8554d0beddc.png)

I realize you warn users not to abuse html attribute configuration, and I will likely be able to solve this by moving to js configuration.

**Comment by enyo** [comment]
Hi,

they should be: `data-ot-tip-joint` and `data-ot-target-joint`

Cheers

**Comment by sethwoodworth** [comment]
Perfect, thank you.  Is that documented anywhere?

**Comment by enyo** [comment]
Yes, when you look at the [documentation](http://www.opentip.org/documentation.html) it says:

> When the document is loaded Opentip scans the document and finds all elements with a data-ot attribute, and instantiates an Opentip automatically. To configure the Opentip this way simply add attributes beginning with data-ot- and the **dashed** option name. Example:
> 
> ``` html
> <div data-ot="The content" data-ot-delay="2" data-ot-hide-trigger="closeButton">Hover me</div>
> ```

**Comment by enyo** [comment]
Epic beard btw :)

**Comment by sethwoodworth** [comment]
Thanks!
