### ISSUE TITLE
Tooltips that automatically reposition with their elements

### ISSUE THREAD

**Issue by nathan-alden-sr** [enyo/opentip#54]
This is actually two feature requests, but I figured since they were related I'd list them here.

I have a tooltip that is associated with a form element. The thing is, the form element is centered in the browser. That means when the user resizes the browser, the tooltip doesn't move. I solved this by doing the following:

$(window).resize(function () {
    $(".opentip-container").reposition();
});

It would be nice if this could be built into the library since I think it's a pretty common scenario.

Also, when using reposition() I noticed that the tooltip lag-slides into place. I want it to remain fixed with the element as the element moves in the window.

**Comment by nathan-alden-sr** [comment]
Argh! I just realized I was missing opentip.css. The moment I included it the laggy transitions disappeared! I still have to include my resize() call to get the tips to maintain their positions, though.

**Comment by nathan-alden-sr** [comment]
Opentip appears to work just as I expect it to after some tweaking. Nice job!

**Comment by enyo** [comment]
Great!
