### ISSUE TITLE
Canvas arrow

### ISSUE THREAD

**Issue by qrczak** [enyo/opentip#55]
Hi,

Where is the part of code which is responsible for canvas arrow? I need to adjust it to my needs.
![screenshot_6_3_13_9_22_pm](https://f.cloud.github.com/assets/97386/601563/6eaaf9a4-cc83-11e2-85e4-d38edd969bf3.png)

**Comment by enyo** [comment]
https://github.com/enyo/opentip/blob/master/src/opentip.coffee#L870

Cheers
