### ISSUE TITLE
Ability to keep tooltip open if cursor is on tooltip itself

### ISSUE THREAD

**Issue by youglobal** [enyo/opentip#56]
I'm not a developer so please excuse my ignorance.

I'd like to know if a problem can be overcome please.

At the moment, I have an icon, which if I mouse over, the tooltip shows. If I move the cursor away from the icon, the tooltip fades away.

If I move the cursor on to the tooltip itself, so away from the icon and on to the tooltip, the tooltip disappears.

The reason I want the tooltip to stay if my cursor remains on the tooltip is so that I can click on a hyperlink within the tooltip, or perhaps even copy the tooltip text. But I do want the tooltip to auto disappear after my is moved away from the icon or the tooltip on display, rather than having to manually click to close.

Can you please tell me if what I am trying to achieve is possible, and if so what needs to be changed ?

Many thanks.

**Comment by youglobal** [comment]
An example of what I want to achieve is at:

http://jquerytools.org/demos/tooltip/any-html.htm

**Comment by enyo** [comment]
Yes it's possible. You can provide multiple "show trigger" to opentip. So if you also provide the `tip` as a show trigger, it should prevent the tooltip from disappearing. Please refer to the docs for more info.

If you don't manage to do it feel free to ask again.

**Comment by youglobal** [comment]
Great, thanks Enyo. I'll see how we go with that suggestion.

**Comment by enyo** [comment]
I'll close this issue for now. Reopen if needed.

**Comment by raj2907** [comment]
hi Enyo,
I have also faced same issue, but I could not able to find the "show trigger" in the document "http://www.opentip.org/documentation.html"

and below is the code i have used to create tool tip 
$(img).opentip(title, {  removeElementsOnHide: true, showOn: "creation",  tipJoint: "bottom", fixed: true, delay: 0, hideDelay: 0, closeButtonOffset: [5, 5], closeButtonRadius: 7, closeButtonCrossSize: 4, background: "rgb(234, 236, 240)", borderColor: "rgb(187, 187, 187)" });

can you please help me?

**Comment by enyo** [comment]
Mh.. Sorry, you're right.

Try adding a hideTrigger for the tip element (mouseout for example). That will automatically generate a show trigger for it.

**Comment by raj2907** [comment]
Thanks Enyo, I have fixed that problem, but it was created another issue, I could able to create multiple layers of the popup on mouse over.
