### ISSUE TITLE
tooltip jolt issue in MacOS Safari browser

### ISSUE THREAD

**Issue by raj2907** [enyo/opentip#59]
When the form first loads, and for a period afterwards, there are screen jolts each time a help icon is moused over. This issue is occurred only on MacOs Safari browser.

Below is the code i have used to open tool tip

$(img).opentip(title, { showEffect: 'blindDown', tipJoint: "top left", removeElementsOnHide: true, stem: true, target: true, tipjoint: ['center', 'top'], hideTrigger: "tip", hideTriggers: ["trigger", "tip"], showOn: "creation", hideOn: "mouseout", fixed: true, background: "rgb(234, 236, 240)", borderColor: "rgb(187, 187, 187)" });

please help me on this.

Regards,
Raj.

**Comment by enyo** [comment]
Could you please post a screenshot and your MacOS + Safari version.
Thx

**Comment by raj2907** [comment]
MacOs version:10.7.5
Safarai browser version: 6.0.4
![screen shot 2013-06-17 at 4 11 04 pm](https://f.cloud.github.com/assets/4636903/661684/e64f9840-d73a-11e2-805a-96fea2e6f16d.png)

**Comment by enyo** [comment]
What do you mean by screen jolt? Might it be caused by the tooltip sticking out of the browser window?

**Comment by raj2907** [comment]
No it's positioning correctly, but Screen flickers on every tool tip item mouse over.

**Comment by enyo** [comment]
I'm really sorry but I have no notion of what could cause the behaviour you're describing (and I'm not quite sure what this behaviour concretely is).

Do you have a link where I could try it out?

**Comment by raj2907** [comment]
I have uploaded website page copy on the below link 
globalpanda.versatile-soft.com/testtooltip.zip

Please to open the page in MacOs and mouse over the help icon, you will see page flickering.

**Comment by enyo** [comment]
Ok, now I see what you mean.

This is a webkit bug, and is caused by webkit switching between gpu and cpu rendering (as far as I could figure out).

If you set those properties on the container form, it will force webkit to always render on the gpu which will prevent the flickering:

``` css
#aspnetForm {
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
}
```
