### ISSUE TITLE
How to specify no hide trigger

### ISSUE THREAD

**Issue by nicolasguenther** [enyo/opentip#62]
I don't want my tooltips to hide by user interaction, just programatically. Unfortunately there is no option for this. I tried setting:

``` javascript
tip.options.hideTriggers = [];
```

on all my tooltips, which seemed to work at first but introduced undeterministic show/hide behavior on mouseover.

**Comment by enyo** [comment]
Setting `hideTrigger` (no s) to `null` should work.

Cheers
