### ISSUE TITLE
Slanted Right Edge When Hiding Close Button

### ISSUE THREAD

**Issue by donlee8** [enyo/opentip#65]
First off just want to say how great this framework is and how easy it is to work with.

I'm using a tooltip as a notification list and would like to hide the close button. I've set the following options:

closeButtonRadius: 0,
closeButtonCrossSize: 0,
closeButtonLinkOverscan: 0

This successfully hides the close button but the tooltip's right edge is slanted now. Here's a screengrab:

![tooltip](https://f.cloud.github.com/assets/2600389/710345/af0ed46e-de78-11e2-94ce-0a93a115bd27.png)

I've highlighted the canvas element in Chrome's JS debugging tool and you can see the right edge is slanted. I understand that it's probably not intended to set the close button properties to 0 but is there any way this can be fixed?

**Comment by enyo** [comment]
Yep you're right.. it shouldn't be set to 0. Although I could have prepared for that scenario I decided against it, since it introduces unnecessary code.

Why do you have a close button in the first place? When you don't set `hideOn: "closeButton"` it won't add a close button.

Hope that helps.

**Comment by donlee8** [comment]
Ahh thanks, that makes sense. I added hideOn: 'load' so it would stay open.

**Comment by pioterj** [comment]
I noticed this effect when having close button enabled. I'd like to have close button completely contained in the tooltip but I ended up with this slant effect.
