### ISSUE TITLE
Wrong code at documentation page

### ISSUE THREAD

**Issue by ahsan-gill** [enyo/opentip#67]
Hello,

To close all open OpenTip instances, the code provided on documentation page do not work.

Here it is:
for(var i = 0; i < Opentip.tips; i ++) { Opentip.tips[i].hide(); }

Whereas it should be:
for(var i = 0; i < Opentip.tips.length; i ++) { Opentip.tips[i].hide(); }

The above code closes all open tip instances. Thanks

**Comment by enyo** [comment]
Thank you! Will fix soon.

**Comment by sandervm** [comment]
Just ran into the same thing :)
