### ISSUE TITLE
How to inspect tooltips with webinspector?

### ISSUE THREAD

**Issue by Metasequ0ia** [enyo/opentip#69]
Maybe I am dumb, but I am not able to access the css rules with webinspector. How is this possible?

**Comment by kcrwfrd** [comment]
Pass these options when you instantiate the tooltip, then you can right click inside of it to inspect the elements:

```
showOn: 'click',
hideOn: 'click',
fixed: true
```

**Comment by Metasequ0ia** [comment]
Thanks kvcrawford! But I use html attributes to create opentips. Is there a way to pass those options when using html attributes?

**Comment by kcrwfrd** [comment]
Sure, set them like this: `data-ot-show-on="click" data-ot-hide-on="click" data-ot-fixed="true"`

**Comment by Metasequ0ia** [comment]
Excellent! Didn't thought it's that easy. Thanks a lot!

**Comment by enyo** [comment]
Thanks @kvcrawford for helping out!

**Comment by kcrwfrd** [comment]
:+1: no problem guys! Happy to help.
