### ISSUE TITLE
Tips never get created on IE < 9, if user adds them inside a window load listener

### ISSUE THREAD

**Issue by nickdaugherty** [enyo/opentip#7]
On IE less than 9, if the user sets up tips inside his own window load listener, the tips never get setup. The reason for this is fairly complicated, but comes down to 2 things: 
- Prototype doesn't check if the event has already happened when listeners are registered...so if the window has already been loaded and a second listener is registered, the second one will _never_ fire.
- On IE < 9, registered events can occur in any order (usually in the reverse that they do on IE 9 and other browsers). 

If the user has an onload listener that configures tips, it can be fired _before_ the Opentip listener (about line 255) that sets Opentip.documentLoaded. If that's the case, the code block around line 92 is executed, but due to the first problem above, that second window load listener never fires, so the tip never gets created.

I'll submit a pull request with a fix shortly.

**Comment by enyo** [comment]
Thanks a lot Nick. I'll look into it and merge it as soon as I have some time (probably next week).
Cheers.
