### ISSUE TITLE
Tooltips have a max-width of 300px

### ISSUE THREAD

**Issue by kcrwfrd** [enyo/opentip#70]
Tooltips with content set to an explicit width via CSS do not size greater than 300px. See an isolated demo at http://jsfiddle.net/kvcrawford/gksSy/1/

Thank you for the plugin, it's very well-written!

**Comment by enyo** [comment]
This is just a CSS property. Overwrite at will!

``` css
.opentip-container {
  max-width: 1000px;
}
```

Thank you, enjoy!

**EDIT**: I just set it to `300px` because I felt that that a fairly intuitive width for a tooltip.

**Comment by kcrwfrd** [comment]
ahh! I was going crazy searching for a max-width somewhere with the inspector. Thanks @enyo
