### ISSUE TITLE
How to get started using the opentip?

### ISSUE THREAD

**Issue by yan-chen** [enyo/opentip#73]
Hi, I have a problem with getting started using the opentip.
I want to use the opentip in my angularjs application. I have downloaded the opentip.css, adapts-jquery.js and popentip.js files and embedded them all, but I was not able to create the tooltip. I tried just using your example:
< div data-ot="The content" data-ot-delay="2" data-ot-hide-trigger="closeButton" >Hover me< /div >
but it did not do anything. 
I know I must be missing some steps or doing something wrong, but I am just now sure what. Can you please help me?
Thank you.

**Comment by misiek08** [comment]
Not only you. I have empty tooltips using opentip-jquery.min.js

**Comment by enyo** [comment]
You have to use the files in the [downloads folder](https://github.com/enyo/opentip/tree/master/downloads). Just use `opentip-jquery.js` and you're good to go.

**Comment by enyo** [comment]
@misiek08 What do you mean empty tooltips? Are you maybe missing the CSS file?

**Comment by misiek08** [comment]
http://max-kino.pl/index.html

Hover Images below Main slider

**Comment by misiek08** [comment]
Oh, designer used jquery 1.3.2. After changing to 2.0.3 works like a charm for me.
