### ISSUE TITLE
Not working in IE7

### ISSUE THREAD

**Issue by elainsun** [enyo/opentip#78]
Hi, I just downloaded latest version of opentip-prototype-excanvas.js. It works on most of my testing browser except IE7. It seems my code missed some dependencies which is using in opentip library. Could you please shed some lights on this issue? 

attached is my test code, it is very simple.

Thanks,
Elaine

**Comment by elainsun** [comment]
It is solved. Sorry it's because of my bad code, not Opentip's issue.

**Comment by enyo** [comment]
Great to hear :)
Cheers
