### ISSUE TITLE
Don't know how to display image as tooltip

### ISSUE THREAD

**Issue by martind1111** [enyo/opentip#79]
I know this can be done, but I don't know how. How to display an image has a tooltip. If I do the following:

&lt;a href="images/Dispel.ashx.jpg" data-ot="Tag info 1" data-ot-group="tags" data-ot-ajax="true"&gt;Tag 1&lt;/a&gt;

What I see as a tooltip is the binary of the image (text gibberish) instead of the image itself.

How can I display an image as a tooltip with opentip?

Martin

**Comment by martind1111** [comment]
I found out how to display an image as a tooltip. The idea is to put an img src in the content property, like this:

&lt;div data-ot="&lt;img src='images/image.jpg'&gt;" data-ot-style="glass"&gt;Hover me&lt;/div&gt;

However, I still have an issue with the rendering. If the image can't display say at the bottom of the window because the "Hover me" label is too close to the bottom, I would expect the tool tip to display above the "Hover me" label. This is not what happens in my case. Is there an option I need to set or some script I need to execute to get this to work? I thought the containInViewport property would control this, but the default is "true", so I expect it should be doing this already.

**Comment by enyo** [comment]
Hi @martind1111 I think this happens, because the image is loaded after Opentip detected the correct dimensions of the tooltip. To make sure that Opentip knows of the correct dimensions, calling `.reposition()` on your Opentip when the image loaded should do the trick.
Cheers
