### ISSUE TITLE
Regarding frameworks

### ISSUE THREAD

**Issue by sjeev** [enyo/opentip#84]
Hello,

Opentip is one of the available  solutions with multiple functions and I like the ajax loading and stem based tooltips.

But I am confused as you mentioned that we need to add framework  manually. Can you write a detailed documentation from beginning.

Thanks!

**Comment by enyo** [comment]
Hi. You don't need to add a framework. You can simply choose to use the Opentip version that fits the framework you want.

For example, if you're already using jQuery, then use `downloads/opentip-jquery.js`. If you're not using any framework at all, then use `downloads/opentip-native.js`. It's as simple as that.

Cheers
