### ISSUE TITLE
deactivate() doesn't work. See http://jsfiddle.net/h3Zq6/1/

### ISSUE THREAD

**Issue by gbmhunter** [enyo/opentip#88]
deactivate() doesn't seem to work, as shown by the example at http://jsfiddle.net/h3Zq6/1/.

**Comment by enyo** [comment]
Hey, that's because you didn't include the CSS.
Here's the working example with the CSS included: http://jsfiddle.net/h3Zq6/15/

**Comment by gbmhunter** [comment]
Weird, that doesn't look anything like the JsFiddle I was using before. It doesn't even call deactivate? And is the CSS important for the deactivate call to work?

**Comment by gbmhunter** [comment]
Here is a good test case... http://jsfiddle.net/gbmhunter/7sMdH/

**Comment by enyo** [comment]
Hi sorry, but this is the same fiddle as before. Before you share you need to press `update` so it saves the changes.

And CSS is absolutely necessary so tooltops properly hide and stuff. But deactivating them should still work.

**Comment by gbmhunter** [comment]
Ahhh, that would of been the problem the first time to.

Try this...http://jsfiddle.net/gbmhunter/7sMdH/2/

**Comment by oskrgg** [comment]
It doesn't work when I initialize the tooltip (`new Opentip(...)`) and inmediately try to `deactivate`. As @gbmhunter mentioned:
> deactivate() doesn't seem to work, as shown by the example at http://jsfiddle.net/h3Zq6/1/.

Any idea?
