### ISSUE TITLE
Change "lib/adapter-component.js" to "lib/adapter-jquery.js" in bower.json

### ISSUE THREAD

**Issue by changalberto** [enyo/opentip#94]
Line 7 of:
https://github.com/enyo/opentip/blob/master/bower.json

Using grunt bower-install (http://stephenplusplus.github.io/grunt-bower-install/) and it's been including the wrong adaptor for me since I'm using jQuery.

Let me know if this is going to be an issue.

Thanks!

**Comment by enyo** [comment]
Mh... well, the jQuery version is not necessary. It's just an addition if you want it. If you want the jQuery specific calls, at the moment you need to include it manually. The only difference will be that you're going to use `$('el').opentip()` instead of `new Opentip()`
