### ISSUE TITLE
opentip.org website demos not working

### ISSUE THREAD

**Issue by dorseyjon** [enyo/opentip#95]
The demos on opentip.org appear to be down - I saw a stack trace error in Firebug involving a CDATA tag, although I'm not sure that's the cause...  I'm evaluating Opentip for a commercial project I'm working on, and so far have been unable to get it working in my own development environment, and can't seem to view demos of them either - not sure what's going on.  Thought I'd post an issue just in case it hasn't been noticed yet.

**Comment by enyo** [comment]
Thanks. It's because GitHub released a new version of Maruku (the markdown parser) which had an error in it. (Wrapped every script in <![CDATA[ comments, although it's not XHTML).

I switched to kramdown as a compiler now.
